### ISSUE TITLE
Grad Shows Definition - 10/28

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#12]
The descriptions are not appearing in the show definition.

**Comment by endgamesimprov** [comment]
I'm not sure I understand 100%, but let me see if it is this.

When the conversion script runs to convert the old data format into the new data format, whichever show child it comes across first will be the data for the show definition. It seems that a handful of graduation shows so happen to be blank because the first instance of that show (aka child) that it came across just so happened to be empty.

Not really an automatic way to solve this. I reversed the order it grabs the shows (by date descending) so that maybe it fixes more of these than it harms under the assumption that newer shows have better descriptions than the first shows when we started using delclose.

**Comment by thekarinoelle** [comment]
It's all looking normal now. but yea, when I wrote this originally, the parent link that was missing the description in the show definition page.
