### ISSUE TITLE
Calendar Bug Cont. - 10/31

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#18]
Hey, I'm still having this issue. 
![Screen Shot 2019-11-01 at 12 07 19 AM](https://user-images.githubusercontent.com/56705710/68008277-9c79aa80-fc3b-11e9-9c0f-1a93185cde8d.png)

_Originally posted by @Kuri-Sauce in https://github.com/endgamesimprov/EgSites/issues/15#issuecomment-548689759_

**Comment by scottendgames** [comment]
Can you please do the F-12 keyboard menu, and in the settings make sure "Disable Caching when Dev Window Open" is selected. The change I made is 100% a client side change. Also, you on chrome?

**Comment by thekarinoelle** [comment]
so I got it work by unchecking disable caching and then rechecking it.

**Comment by scottendgames** [comment]
Awesome, this as I've mentioned are all client side. As a website, we can't force a person's browser to render it a certain way. Every so often (not sure the timing, but seems to be counted in days) the client browser does check for updates, but until then, it can't be forced easily. So others wont experience this since they will have never gone to the pages in a previous version.
