### ISSUE TITLE
Payroll report showing incorrect rate and roles for some employees.

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#58]
![Screen Shot 2019-11-22 at 11 01 30 PM](https://user-images.githubusercontent.com/56705710/69474989-54eac800-0d7c-11ea-8f13-5e6ebf0b4baf.png)
![Screen Shot 2019-11-22 at 11 02 01 PM](https://user-images.githubusercontent.com/56705710/69474990-54eac800-0d7c-11ea-9092-7c40367b350f.png)

**Comment by endgamesimprov** [comment]
Fixed. You can test in ADV. I corrected both the fact that rates and venues didn't show up in the pull-down if they were not part of the members specific set of rates. This might occur if someone once was a role, but no longer has it. Also made it so "locked" time sheets cannot be edited. Accidentally forgot to implement this feature. The button to lock time sheets wasn't working either, but this was because of another recent change, so fixed this before it went live.
