### ISSUE TITLE
Paypal - 10/17

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#6]
Create button doesn't seem to work. No notification. Refresh, nothing changes.

**Comment by endgamesimprov** [comment]
I'm putting in a lot of hacks in some areas where my old code and my new code have to mix. Paypal logic is sadly still one of those places. Since paypal logic is going away once I figure out how to connect to a smarter payment system, i'd rather not waste the time re-coding it all in the new code just to have it go away. But suffice it to say, I goofed and created a issue with this page after i was done testing it. Should be good now.
