### ISSUE TITLE
Timesheet Page for Non-Admins? - 10/18

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#7]
- Where can employees view their created timesheets? Not seeing it when logged in only as a Stage Manager or Teacher.
- Can non-admins create a timesheet for an event that has already passed it's end time?
- Is the Agenda page the only place to create a new timesheet?

**Comment by scottendgames** [comment]
- There is a tab at the top called "Time Sheet". Sorry, I realized that I still had code which was using the old permissions system. They should all be viewable now.

- Employees need to always be able to create time sheets regardless. If they worked it, they need to be able to create it. But at present, no they cannot go back and create a time sheet from an event that passed (I think it is 6 hours then it disappears). I believe this is the right behavior because in the future we are going to have messaging alarms that are sent to us and this will be a pretty big deal if they don't check-in.

- The Agenda page is the only place to create new time sheets and simultaneously check-in. The "time sheet" tab is the other place.
