### ISSUE TITLE
John Fernandes Enrollment Lost, 101 Wed page showing code

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#75]
https://endgames.slack.com/archives/D5T4J54JU/p1577737269000800

- I got him enrolled in 201 using the alumni email he used to purchase the class.
- I updated this enrollment with the other address he had with 101.
- The 101 enrollment then disappeared and the 101 offering page went wonky.
- I went back and changed the email back to the alumni one to see if the 101 enrollment would reappear, and it didn't.
- I also deleted that 201 enrollment to see if the old one would reappear. It didn't work.

**Comment by endgamesimprov** [comment]
Hi Kari. So the reason this occurred (prepare for pedantic explanation) is because I didn't realize that when I tell the database table that a specific field is a unique value (in this case, the email field), and then another record uses that exact same value, it blows away any other matches to make sure the uniqueness is preserved. I have now put in a check for duplicate emails, and if it exists, it just throws an error in the top box.

Fyi, I need to make the "success" and "failed" boxes a little more different. Instead of everything green, i need to make it red so it catches your eye. I also need to make it so it is always on screen and not just somewhere random.

Please test the corrected issue in DEV, but it is already pushed to DELCLOSE.

**Comment by endgamesimprov** [comment]
I'll be fixing John Fernandes record manually in a moment. But let me know if you find others.
