### ISSUE TITLE
Attendance Audit - 10/18

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#8]
- The day of the week would be very useful (more so than location) especially for teachers who team the same class on multiple days. 
- Does this page include staff that hasn't clocked in?

**Comment by scottendgames** [comment]
- Added! Thanks for the helpful suggestion
- This page intentionally doesn't care for some roles, audiance or producer for example. These roles don't need to be there and it isn't disasterous if they are not. The ones it cares about are (copied from code:
'Stage Manager',
'Front of House',
'Teacher',
'Coach',
'Student',
'Workshop Teacher'

Just FYI, you can see the list of all roles in the 'Admin->Roles' tab if you want to see if there are any others that you'd want to track. 

Do note that this clearly ignores two things (which are future items needed):
1. What if there are two teachers because one is a substitute? It doesn't take into consideration if another teacher checked in. 
2. What if there is a 'producer' training, and we'd want to be notified if they aren't there for those trainings. We currently have no way to be alerted of that fact.
