### ISSUE TITLE
URL Calendar potentially not updating correctly

### ISSUE THREAD

**Issue by thekarinoelle** [endgamesimprov/EgSites#81]
My URL calendar link copied to my personal calendar seems to not be showing the most recent changes on delclose. 

![Screen Shot 2020-01-06 at 3 54 39 PM](https://user-images.githubusercontent.com/56705710/71857598-f4e68180-309c-11ea-850e-d699f5fe87d9.png)
![Screen Shot 2020-01-06 at 3 55 03 PM](https://user-images.githubusercontent.com/56705710/71857599-f57f1800-309c-11ea-848b-f79de9504cba.png)
I removed the URL calendar from my personal calendar, copied and pasted the most recent one from my profile page, and it still shows the old schedule before I made the updates.

**Comment by scottendgames** [comment]
Have you waited like 16 hours? There is a chance this is a client side issue. For example, google chooses not to update until 8 or 16 hours, because if they did every few minutes, they'd be paying a fortune in bandwidth costs for a free service. Even removing the link and adding it back does not solve it.

**Comment by thekarinoelle** [comment]
Ah! Yes, that was the issue. I forgot it was that long. My brain figured it was like an hour delay. All seems good now. It might be good to have this as a reminder somewhere on delclose in case people add it to their personal calendars. Not the highest priority, but food for thought.
